### ISSUE TITLE
[E2E] Error decrypting image

### ISSUE THREAD

**Issue by axelsimon** [aperezdc/revolt#72] opened 2017-07-20 13:29 UTC
Hi,
I'm getting the following error with images sent to me in a one to one room:
>Error decrypting image

The room is end-to-end encrypted and I can read messages fine from Revolt, but images are not visible.
From Riot, I can see the images in the same conversation just fine.

Any ideas?
Let me know if I can submit more info.

Thanks.

**Comment by aperezdc** [comment] 2017-07-28 10:10
I can reproduce this, and I suspect it might be due to the fact that WebKitGTK+ is missing a WebCrypto implementation (see #53 for more), though I am not 100% sure that's the reason. I'll need to take a look.

**Comment by uhoreg** [comment] 2017-08-22 20:36
This is probably a duplicate of #34

**Comment by aperezdc** [comment] 2017-09-23 20:41
I have pushed a new version to the Flatpak repository (`0ec092f400dd`) which uses the GNOME 3.26 runtime, which in turn includes WebKitGTK+ 2.18 with WebCrypto support. In my testing it just showed images in encrypted rooms just fine:

![screenshot from 2017-09-23 23-39-09](https://user-images.githubusercontent.com/723451/30776951-a05e3cc8-a0b8-11e7-8163-344a4a2669a0.png)

@axelsimon: Could you try the updated version? Flatpak may ask you to install the newer runtime as well during installation.

**Comment by aperezdc** [comment] 2017-11-16 09:42
@axelsimon: Ping. Could you please confirm that decryption of images in E2E rooms works now for you?

**Comment by axelsimon** [comment] 2017-11-28 13:54
Hi @aperezdc, sorry for the slow reply. 
I have updated my flatpak and am running the latest Revolt (AFAICT).

I can't test on new messages right now, as my encrypted chats all get the ```Unable to decrypt: the sender has not sent us the keys for this message.``` error message.

However an encrypted image sent 2 weeks ago in an encrypted chat shows up fine, so I think the issue is solved yes.
Thanks!

**Comment by aperezdc** [comment] 2018-02-12 19:07
@axelsimon: The error message is unrelated, I think, and upstream has been slashing bugs which caused that kind of error.

Closing the issue as decrypting images has been working fine for a good while.

**Closed by aperezdc** 2018-02-12 19:07 UTC
Labels: bug, infoneeded
