### ISSUE TITLE
Room directory icon changes

### ISSUE THREAD

**Issue by uhoreg** [aperezdc/revolt#45] opened 2017-02-19 01:06 UTC
(was [vector-im/riot-web#3023](https://github.com/vector-im/riot-web/issues/3023), but does not seem to be happening in Riot desktop or in other browsers, so it may be a bug in Revolt)

The room directory icon starts out with an "empty" middle:
![image](https://cloud.githubusercontent.com/assets/1012976/22183707/d5deb838-e091-11e6-9a77-3dfa6344db12.png)
If I mouse over it (or mouse over certain other things), the middle gets filled in, like this:
![image](https://cloud.githubusercontent.com/assets/1012976/22183758/275e60e0-e093-11e6-83e7-a88b45745ab7.png)
The same issue might also be causing this in the dark theme:
![image](https://cloud.githubusercontent.com/assets/1012976/22344232/5dc5e1b0-e3c9-11e6-822f-76c86cf13675.png)

**Comment by aperezdc** [comment] 2017-03-01 10:30
I have not been able to reproduce this myself, but there is indeed some rendering glitches. For example here I see the following:

![screenshot from 2017-03-01 12-27-16](https://cloud.githubusercontent.com/assets/723451/23456047/8eee0058-fe7a-11e6-9dbe-e504df67fe27.png)

Most likely this is going to be some issue in WebKitGTK+, because the same happens in Epiphany and other browsers based on it. I will try to pin this down at some point and open an upstream bug if so needed.

**Comment by uhoreg** [comment] 2017-04-03 19:24
Sorry, I missed your question.  I was using Revolt as Flatpak

```
$ flatpak info org.perezdecastro.Revolt 
app/org.perezdecastro.Revolt/x86_64/master org.perezdecastro.Revolt-origin dcef3a0a191e80dc1fdafc4d03f5f512c949cd91a55f6b390a16f2bf27859bbd
```

**Comment by aperezdc** [comment] 2017-04-03 21:10
@uhoreg: Thanks for commenting, that version of the Flatpak is running against the 3.22 runtime, which has WebKitGTK+ 2.14.x

I have updated the JSON manifest and uploaded a new version a few days ago which uses the 3.24 runtime, which has WebKitGTK+ 2.16.x, but the same rendering issue happens. It seems that the rendering issue is still not fixed in WebKitGTK+.

**Comment by aperezdc** [comment] 2017-05-05 14:04
In the Riot `develop` branch the icon has been changed, and the new one displays correctly in Revolt:

![new-sidebar-icons](https://cloud.githubusercontent.com/assets/723451/25748745/d58c9d7c-31b4-11e7-8300-718a7aef7dd4.png)

**Comment by aperezdc** [comment] 2017-05-24 18:53
Riot 0.9.10 is now out, and it uses the new icon. I think we can close this :wink:

**Closed by aperezdc** 2017-05-24 18:53 UTC
Labels: bug, infoneeded
