### ISSUE TITLE
Open URI window handling

### ISSUE THREAD

**Issue by allanday** [aperezdc/revolt#49] opened 2017-03-17 16:37 UTC
I regularly observe the following when opening links with Revolt:

  * The dialog is hidden behind the app window when it opens (you get an "is ready" notification for it, which although is technically wrong, does allow you to raise the window)
  * When you do raise the dialog window, it is located in the top-left corner of the display
  * The dialog window isn't modal to the app that called it
  * When the dialog is focused, the app menu reads "Xdg-desktop-portal-gtk" and has a missing icon

According to https://github.com/flatpak/xdg-desktop-portal-gtk/issues/56#issuecomment-287391270 , using gtk_show_uri_on_window should resolve these issues.

**Comment by jscurtu** [comment] 2017-03-17 19:30
@allanday looks like it already has been implemented.
https://github.com/aperezdc/revolt/commit/a12dbd565005e229adef8571cb396e87bca0fd00

The flatpak might not been updated yet..

**Comment by aperezdc** [comment] 2017-03-18 19:30
@jscurtu: You are right, I forgot to mark this issue as duplicate of #31.

@allanday: The latest Flatpak build should have the fix in it. Could you please confirm that it works for you?

**Comment by aperezdc** [comment] 2017-05-24 18:40
@allanday: I am going to assume that this is now working for you as well — this has been working fine for many of us at Igalia, so I am going to close the ticket; please feel free to re-open if needed.

**Closed by aperezdc** 2017-05-24 18:40 UTC
Labels: duplicate, qa
