### ISSUE TITLE
Tray icon doesn't appear on GNOME 3.24 + Wayland sessions

### ISSUE THREAD

**Issue by jaragunde** [aperezdc/revolt#69] opened 2017-07-11 14:14 UTC
The Revolt tray icon doesn't appear when using it on a GNOME 3.24 session on Wayland (Fedora 26). Other applications with systray icons (e.g. Pidgin) seem to behave normally. Falling back to an X11 session fixes the problem.

Oddly enough, in the previous Fedora release (25, with GNOME 3.22), it worked properly both on X11 and Wayland.

**Comment by aperezdc** [comment] 2017-07-11 15:02
`GtkStatusIcon` is not supposed to work in Wayland. It could be that the other applications you mention do _not_ use `GtkStatusIcon` but some other mechanism.

What should work in Wayland is the `StatusNotification` support, if you install the [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) Shell extension. Could you try that?

**Comment by jaragunde** [comment] 2017-07-13 11:28
> GtkStatusIcon is not supposed to work in Wayland. It could be that the other applications you mention do not use GtkStatusIcon but some other mechanism.

I'm checking with a colleague here who's using a GNOME on Wayland session on F25. Any applications that use the status icon appear correctly on the tray, even Revolt. No GNOME extensions seem to be involved in that, and I don't think every app out there is supporting multiple mechanisms. Also tried Linphone and Pidgin.

> What should work in Wayland is the StatusNotification support, if you install the KStatusNotifierItem/AppIndicator Support Shell extension. Could you try that?

That works, indeed.

**Comment by jaragunde** [comment] 2017-07-14 09:06
> I'm checking with a colleague here who's using a GNOME on Wayland session on F25. Any applications that use the status icon appear correctly on the tray, even Revolt. 

This bit of information was wrong, sorry for the noise. It was an X11 session.

It's true, though, that Linphone and Pidgin show tray icons on Wayland sessions, I don't know what API they are using for that.

**Comment by kwill** [comment] 2017-11-13 08:48
I can confirm that using the latest Flatpak package + GNOME 3.26.2 + Wayland 1.14.0 + PureOS 8.0 (~= Debian main testing), I do get a system tray icon for Revolt. Happy to provide additional system details if that would be helpful.

**Comment by aperezdc** [comment] 2017-11-16 09:46
@kwill: Thanks a lot for confirming. It has been working for me as well :wink: 

@jaragunde: Could you please confirm that the issue is solved for you as well?

**Comment by jaragunde** [comment] 2018-03-06 12:18
Fixed here too. Thanks and sorry for the delay.

**Comment by aperezdc** [comment] 2018-03-06 15:43
@jaragunde: No problem! Thanks for the confirmation, let's then close this issue :+1:

**Closed by aperezdc** 2018-03-06 15:43 UTC
Labels: infoneeded
